/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Engine {
  constructor()
  parse(schema: any, value: any): any
  toJsonSchema(schema: any): any
  toolRegister(spec: any): void
  toolRegisterWith(spec: any, replace: boolean): void
  toolList(): any
  toolPrepare(name: string, caller: any, args: any): any
  agentStart(config: any, user: string): any
  agentContinue(config: any, messages: any): any
  agentDecide(runId: string, decision: any): any
  agentToolResults(runId: string, results: any): any
  agentGet(runId: string): any | null
  graphRegister(def: any): void
  graphRegisterWith(def: any, replace: boolean): void
  graphUnregister(name: string): boolean
  graphStart(name: string, state: any): any
  graphAdvance(runId: string): any
  graphCompleteNode(runId: string, nodeId: string, output?: string | undefined | null, statePatch?: any | undefined | null): any
  graphFailNode(runId: string, error: string): any
  graphResumeInterrupt(runId: string): any
  graphCompleteInterrupt(runId: string, decision: string): any
  graphRoute(runId: string, to: string): any
  graphGet(runId: string): any | null
  graphCheckpointExport(runId: string): any
  graphCheckpointRestore(blob: any): any
  graphDrop(runId: string): boolean
  agentDrop(runId: string): boolean
  workflowRegister(def: any): void
  workflowStart(name: string): any
  workflowAdvance(runId: string): any
  workflowCompleteStep(runId: string, key?: string | undefined | null, value?: string | undefined | null): any
  workflowFailStep(runId: string, error: string): any
  workflowResumeHuman(runId: string): any
}
